// Generated by hand from supabase/migrations/001_initial_schema.sql and
// 002_predictions_models.sql. Keep in sync with migrations.
// When the Supabase CLI can reach the remote DB, regenerate with:
//   npx supabase gen types typescript --project-id shwylcfhxmrunwjbunnf --schema public > types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      trusted_analysts: {
        Row: {
          id: string;
          uw_analyst_id: string;
          name: string;
          firm: string;
          tier: number;
          sectors: string[] | null;
          confidence_score: number;
          notes: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          uw_analyst_id: string;
          name: string;
          firm: string;
          tier: number;
          sectors?: string[] | null;
          confidence_score: number;
          notes?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          uw_analyst_id?: string;
          name?: string;
          firm?: string;
          tier?: number;
          sectors?: string[] | null;
          confidence_score?: number;
          notes?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      rating_events: {
        Row: {
          id: string;
          analyst_id: string;
          ticker: string;
          action_type:
            | 'initiation'
            | 'upgrade'
            | 'downgrade'
            | 'pt_change'
            | 'reiteration'
            | 'suspension';
          old_rating: string | null;
          new_rating: string | null;
          old_pt: number | null;
          new_pt: number | null;
          implied_upside: number | null;
          published_at: string;
          source: string;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          analyst_id: string;
          ticker: string;
          action_type:
            | 'initiation'
            | 'upgrade'
            | 'downgrade'
            | 'pt_change'
            | 'reiteration'
            | 'suspension';
          old_rating?: string | null;
          new_rating?: string | null;
          old_pt?: number | null;
          new_pt?: number | null;
          implied_upside?: number | null;
          published_at: string;
          source?: string;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          analyst_id?: string;
          ticker?: string;
          action_type?:
            | 'initiation'
            | 'upgrade'
            | 'downgrade'
            | 'pt_change'
            | 'reiteration'
            | 'suspension';
          old_rating?: string | null;
          new_rating?: string | null;
          old_pt?: number | null;
          new_pt?: number | null;
          implied_upside?: number | null;
          published_at?: string;
          source?: string;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      event_features: {
        Row: {
          event_id: string;
          spot_price: number | null;
          prev_close: number | null;
          adv_30d: number | null;
          market_cap: number | null;
          sector: string | null;
          sector_etf: string | null;
          sector_etf_level: number | null;
          spy_level: number | null;
          vix: number | null;
          days_to_earnings: number | null;
          days_since_last_rating: number | null;
          analyst_coverage_count: number | null;
          short_interest_pct: number | null;
          iv_30d: number | null;
          pre_market_return: number | null;
          analyst_tier: number | null;
          analyst_hit_rate_90d: number | null;
          analyst_avg_return_90d: number | null;
          implied_upside: number | null;
          pt_change_pct: number | null;
          is_initiation: boolean | null;
          is_top_pick: boolean | null;
          regime: 'bull' | 'bear' | 'chop' | null;
          captured_at: string;
        };
        Insert: {
          event_id: string;
          spot_price?: number | null;
          prev_close?: number | null;
          adv_30d?: number | null;
          market_cap?: number | null;
          sector?: string | null;
          sector_etf?: string | null;
          sector_etf_level?: number | null;
          spy_level?: number | null;
          vix?: number | null;
          days_to_earnings?: number | null;
          days_since_last_rating?: number | null;
          analyst_coverage_count?: number | null;
          short_interest_pct?: number | null;
          iv_30d?: number | null;
          pre_market_return?: number | null;
          analyst_tier?: number | null;
          analyst_hit_rate_90d?: number | null;
          analyst_avg_return_90d?: number | null;
          implied_upside?: number | null;
          pt_change_pct?: number | null;
          is_initiation?: boolean | null;
          is_top_pick?: boolean | null;
          regime?: 'bull' | 'bear' | 'chop' | null;
          captured_at?: string;
        };
        Update: {
          event_id?: string;
          spot_price?: number | null;
          prev_close?: number | null;
          adv_30d?: number | null;
          market_cap?: number | null;
          sector?: string | null;
          sector_etf?: string | null;
          sector_etf_level?: number | null;
          spy_level?: number | null;
          vix?: number | null;
          days_to_earnings?: number | null;
          days_since_last_rating?: number | null;
          analyst_coverage_count?: number | null;
          short_interest_pct?: number | null;
          iv_30d?: number | null;
          pre_market_return?: number | null;
          analyst_tier?: number | null;
          analyst_hit_rate_90d?: number | null;
          analyst_avg_return_90d?: number | null;
          implied_upside?: number | null;
          pt_change_pct?: number | null;
          is_initiation?: boolean | null;
          is_top_pick?: boolean | null;
          regime?: 'bull' | 'bear' | 'chop' | null;
          captured_at?: string;
        };
        Relationships: [];
      };
      price_snapshots: {
        Row: {
          id: string;
          event_id: string;
          ticker: string;
          window_label:
            | 't0'
            | 't+1m'
            | 't+2m'
            | 't+5m'
            | 't+30m'
            | 'eod'
            | 't+1d'
            | 't+5d'
            | 't+30d';
          price: number | null;
          spy_price: number | null;
          sector_etf_price: number | null;
          volume: number | null;
          captured_at: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          ticker: string;
          window_label:
            | 't0'
            | 't+1m'
            | 't+2m'
            | 't+5m'
            | 't+30m'
            | 'eod'
            | 't+1d'
            | 't+5d'
            | 't+30d';
          price?: number | null;
          spy_price?: number | null;
          sector_etf_price?: number | null;
          volume?: number | null;
          captured_at?: string | null;
        };
        Update: {
          id?: string;
          event_id?: string;
          ticker?: string;
          window_label?:
            | 't0'
            | 't+1m'
            | 't+2m'
            | 't+5m'
            | 't+30m'
            | 'eod'
            | 't+1d'
            | 't+5d'
            | 't+30d';
          price?: number | null;
          spy_price?: number | null;
          sector_etf_price?: number | null;
          volume?: number | null;
          captured_at?: string | null;
        };
        Relationships: [];
      };
      price_bars: {
        Row: {
          id: string;
          event_id: string;
          ticker: string;
          bar_timestamp: string;
          granularity: 'second' | 'minute' | 'daily';
          open: number | null;
          high: number | null;
          low: number | null;
          close: number | null;
          volume: number | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          ticker: string;
          bar_timestamp: string;
          granularity: 'second' | 'minute' | 'daily';
          open?: number | null;
          high?: number | null;
          low?: number | null;
          close?: number | null;
          volume?: number | null;
        };
        Update: {
          id?: string;
          event_id?: string;
          ticker?: string;
          bar_timestamp?: string;
          granularity?: 'second' | 'minute' | 'daily';
          open?: number | null;
          high?: number | null;
          low?: number | null;
          close?: number | null;
          volume?: number | null;
        };
        Relationships: [];
      };
      virtual_trades: {
        Row: {
          id: string;
          event_id: string;
          strategy: 'immediate' | 'fade' | 'drift';
          entry_window: string;
          exit_window: string;
          entry_price: number | null;
          exit_price: number | null;
          raw_return: number | null;
          market_adj_return: number | null;
          sector_adj_return: number | null;
          cost_adjusted_return: number | null;
          estimated_slippage_bps: number | null;
          estimated_borrow_cost_bps: number | null;
          status: 'pending' | 'filled' | 'closed' | 'failed';
          failure_reason: string | null;
          created_at: string;
          closed_at: string | null;
        };
        Insert: {
          id?: string;
          event_id: string;
          strategy: 'immediate' | 'fade' | 'drift';
          entry_window: string;
          exit_window: string;
          entry_price?: number | null;
          exit_price?: number | null;
          raw_return?: number | null;
          market_adj_return?: number | null;
          sector_adj_return?: number | null;
          cost_adjusted_return?: number | null;
          estimated_slippage_bps?: number | null;
          estimated_borrow_cost_bps?: number | null;
          status?: 'pending' | 'filled' | 'closed' | 'failed';
          failure_reason?: string | null;
          created_at?: string;
          closed_at?: string | null;
        };
        Update: {
          id?: string;
          event_id?: string;
          strategy?: 'immediate' | 'fade' | 'drift';
          entry_window?: string;
          exit_window?: string;
          entry_price?: number | null;
          exit_price?: number | null;
          raw_return?: number | null;
          market_adj_return?: number | null;
          sector_adj_return?: number | null;
          cost_adjusted_return?: number | null;
          estimated_slippage_bps?: number | null;
          estimated_borrow_cost_bps?: number | null;
          status?: 'pending' | 'filled' | 'closed' | 'failed';
          failure_reason?: string | null;
          created_at?: string;
          closed_at?: string | null;
        };
        Relationships: [];
      };
      event_context: {
        Row: {
          id: string;
          event_id: string;
          context_type:
            | 'news'
            | 'filing'
            | 'followon_rating'
            | 'earnings'
            | 'halt'
            | 'corporate_action'
            | 'm_and_a';
          occurred_at: string;
          source: string | null;
          headline: string | null;
          raw_payload: Json | null;
          flagged_as_confound: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          context_type:
            | 'news'
            | 'filing'
            | 'followon_rating'
            | 'earnings'
            | 'halt'
            | 'corporate_action'
            | 'm_and_a';
          occurred_at: string;
          source?: string | null;
          headline?: string | null;
          raw_payload?: Json | null;
          flagged_as_confound?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          context_type?:
            | 'news'
            | 'filing'
            | 'followon_rating'
            | 'earnings'
            | 'halt'
            | 'corporate_action'
            | 'm_and_a';
          occurred_at?: string;
          source?: string | null;
          headline?: string | null;
          raw_payload?: Json | null;
          flagged_as_confound?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      event_notes: {
        Row: {
          id: string;
          event_id: string;
          note: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          note: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          note?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      models: {
        Row: {
          version: string;
          algorithm: string;
          trained_at: string;
          training_set_size: number | null;
          training_window_start: string | null;
          training_window_end: string | null;
          features: string[] | null;
          hyperparameters: Json | null;
          oos_metrics: Json | null;
          notes: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: {
          version: string;
          algorithm: string;
          trained_at: string;
          training_set_size?: number | null;
          training_window_start?: string | null;
          training_window_end?: string | null;
          features?: string[] | null;
          hyperparameters?: Json | null;
          oos_metrics?: Json | null;
          notes?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          version?: string;
          algorithm?: string;
          trained_at?: string;
          training_set_size?: number | null;
          training_window_start?: string | null;
          training_window_end?: string | null;
          features?: string[] | null;
          hyperparameters?: Json | null;
          oos_metrics?: Json | null;
          notes?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      predictions: {
        Row: {
          id: string;
          event_id: string;
          model_version: string;
          horizon: '30m' | 'eod' | '1d' | '5d' | '30d';
          predicted_direction: 'up' | 'down' | 'flat';
          predicted_return: number | null;
          predicted_return_p10: number | null;
          predicted_return_p50: number | null;
          predicted_return_p90: number | null;
          predicted_prob_positive: number | null;
          confidence_bucket: string | null;
          feature_snapshot: Json;
          recommended_kelly_fraction: number | null;
          predicted_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          model_version: string;
          horizon: '30m' | 'eod' | '1d' | '5d' | '30d';
          predicted_direction: 'up' | 'down' | 'flat';
          predicted_return?: number | null;
          predicted_return_p10?: number | null;
          predicted_return_p50?: number | null;
          predicted_return_p90?: number | null;
          predicted_prob_positive?: number | null;
          confidence_bucket?: string | null;
          feature_snapshot: Json;
          recommended_kelly_fraction?: number | null;
          predicted_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          model_version?: string;
          horizon?: '30m' | 'eod' | '1d' | '5d' | '30d';
          predicted_direction?: 'up' | 'down' | 'flat';
          predicted_return?: number | null;
          predicted_return_p10?: number | null;
          predicted_return_p50?: number | null;
          predicted_return_p90?: number | null;
          predicted_prob_positive?: number | null;
          confidence_bucket?: string | null;
          feature_snapshot?: Json;
          recommended_kelly_fraction?: number | null;
          predicted_at?: string;
        };
        Relationships: [];
      };
      prediction_outcomes: {
        Row: {
          prediction_id: string;
          actual_return: number | null;
          actual_market_adj_return: number | null;
          actual_direction: 'up' | 'down' | 'flat' | null;
          was_correct_direction: boolean | null;
          hit_p10_p90_band: boolean | null;
          squared_error: number | null;
          log_loss_contribution: number | null;
          resolved_at: string;
        };
        Insert: {
          prediction_id: string;
          actual_return?: number | null;
          actual_market_adj_return?: number | null;
          actual_direction?: 'up' | 'down' | 'flat' | null;
          was_correct_direction?: boolean | null;
          hit_p10_p90_band?: boolean | null;
          squared_error?: number | null;
          log_loss_contribution?: number | null;
          resolved_at?: string;
        };
        Update: {
          prediction_id?: string;
          actual_return?: number | null;
          actual_market_adj_return?: number | null;
          actual_direction?: 'up' | 'down' | 'flat' | null;
          was_correct_direction?: boolean | null;
          hit_p10_p90_band?: boolean | null;
          squared_error?: number | null;
          log_loss_contribution?: number | null;
          resolved_at?: string;
        };
        Relationships: [];
      };
      analyst_scorecards: {
        Row: {
          id: string;
          analyst_id: string;
          strategy: 'immediate' | 'fade' | 'drift';
          lookback_days: 0 | 30 | 90 | 365;
          event_count: number;
          hit_rate: number | null;
          avg_return: number | null;
          median_return: number | null;
          avg_market_adj_return: number | null;
          median_market_adj_return: number | null;
          max_drawdown: number | null;
          sharpe: number | null;
          sortino: number | null;
          computed_at: string;
        };
        Insert: {
          id?: string;
          analyst_id: string;
          strategy: 'immediate' | 'fade' | 'drift';
          lookback_days: 0 | 30 | 90 | 365;
          event_count: number;
          hit_rate?: number | null;
          avg_return?: number | null;
          median_return?: number | null;
          avg_market_adj_return?: number | null;
          median_market_adj_return?: number | null;
          max_drawdown?: number | null;
          sharpe?: number | null;
          sortino?: number | null;
          computed_at?: string;
        };
        Update: {
          id?: string;
          analyst_id?: string;
          strategy?: 'immediate' | 'fade' | 'drift';
          lookback_days?: 0 | 30 | 90 | 365;
          event_count?: number;
          hit_rate?: number | null;
          avg_return?: number | null;
          median_return?: number | null;
          avg_market_adj_return?: number | null;
          median_market_adj_return?: number | null;
          max_drawdown?: number | null;
          sharpe?: number | null;
          sortino?: number | null;
          computed_at?: string;
        };
        Relationships: [];
      };
      calibration_metrics: {
        Row: {
          id: string;
          model_version: string;
          horizon: string;
          bucket_label: string;
          predictions_count: number;
          actual_positive_rate: number | null;
          expected_positive_rate: number | null;
          brier_score: number | null;
          log_loss: number | null;
          computed_at: string;
        };
        Insert: {
          id?: string;
          model_version: string;
          horizon: string;
          bucket_label: string;
          predictions_count: number;
          actual_positive_rate?: number | null;
          expected_positive_rate?: number | null;
          brier_score?: number | null;
          log_loss?: number | null;
          computed_at?: string;
        };
        Update: {
          id?: string;
          model_version?: string;
          horizon?: string;
          bucket_label?: string;
          predictions_count?: number;
          actual_positive_rate?: number | null;
          expected_positive_rate?: number | null;
          brier_score?: number | null;
          log_loss?: number | null;
          computed_at?: string;
        };
        Relationships: [];
      };
      drift_alerts: {
        Row: {
          id: string;
          model_version: string;
          feature_name: string | null;
          test_type: string | null;
          test_statistic: number | null;
          p_value: number | null;
          threshold: number | null;
          triggered: boolean;
          detected_at: string;
          resolved_at: string | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          model_version: string;
          feature_name?: string | null;
          test_type?: string | null;
          test_statistic?: number | null;
          p_value?: number | null;
          threshold?: number | null;
          triggered: boolean;
          detected_at?: string;
          resolved_at?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          model_version?: string;
          feature_name?: string | null;
          test_type?: string | null;
          test_statistic?: number | null;
          p_value?: number | null;
          threshold?: number | null;
          triggered?: boolean;
          detected_at?: string;
          resolved_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      market_regimes: {
        Row: {
          trading_date: string;
          regime: 'bull' | 'bear' | 'chop';
          spy_trend_50d: number | null;
          vix_level: number | null;
          notes: string | null;
          computed_at: string;
        };
        Insert: {
          trading_date: string;
          regime: 'bull' | 'bear' | 'chop';
          spy_trend_50d?: number | null;
          vix_level?: number | null;
          notes?: string | null;
          computed_at?: string;
        };
        Update: {
          trading_date?: string;
          regime?: 'bull' | 'bear' | 'chop';
          spy_trend_50d?: number | null;
          vix_level?: number | null;
          notes?: string | null;
          computed_at?: string;
        };
        Relationships: [];
      };
      prediction_overrides: {
        Row: {
          id: string;
          prediction_id: string;
          override_direction: 'up' | 'down' | 'flat' | 'skip' | null;
          override_size_fraction: number | null;
          reasoning: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          prediction_id: string;
          override_direction?: 'up' | 'down' | 'flat' | 'skip' | null;
          override_size_fraction?: number | null;
          reasoning: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          prediction_id?: string;
          override_direction?: 'up' | 'down' | 'flat' | 'skip' | null;
          override_size_fraction?: number | null;
          reasoning?: string;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

// Convenience aliases used throughout the app
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
