import type { UwTipranksRow } from './types';

/**
 * Fallback rows used only when `uw_tipranks_analysis` is missing or empty
 * (fresh clone, migration not applied yet, ingest hasn't run). The page shows
 * a banner whenever these are on screen so they're never mistaken for live data.
 */
const RAW: Omit<UwTipranksRow, 'id' | 'as_of'>[] = [
  {
    ticker: 'NVDA',
    company: 'NVIDIA Corp',
    sector: 'Technology',
    price: 178.42,
    uw_sentiment: 'bullish',
    uw_net_premium: 42_800_000,
    uw_call_put_ratio: 2.41,
    uw_unusual_score: 92,
    uw_iv_rank: 61,
    uw_dark_pool_pct: 44.2,
    tr_consensus: 'strong_buy',
    tr_analyst_count: 41,
    tr_star_rating: 4.5,
    tr_price_target: 215.0,
    tr_upside_pct: 20.5,
    tr_success_rate: 71.4,
    tr_avg_return: 28.6,
    composite_score: 88,
    signal: 'aligned_bull',
    notes: 'Call sweeps into Oct expiry; consensus PT raised twice this month.',
  },
  {
    ticker: 'AAPL',
    company: 'Apple Inc',
    sector: 'Technology',
    price: 241.18,
    uw_sentiment: 'neutral',
    uw_net_premium: 3_100_000,
    uw_call_put_ratio: 1.08,
    uw_unusual_score: 38,
    uw_iv_rank: 24,
    uw_dark_pool_pct: 51.7,
    tr_consensus: 'buy',
    tr_analyst_count: 34,
    tr_star_rating: 4.0,
    tr_price_target: 262.5,
    tr_upside_pct: 8.8,
    tr_success_rate: 66.2,
    tr_avg_return: 14.1,
    composite_score: 61,
    signal: 'neutral',
    notes: 'Flow flat, analysts mildly constructive.',
  },
  {
    ticker: 'TSLA',
    company: 'Tesla Inc',
    sector: 'Consumer Cyclical',
    price: 396.55,
    uw_sentiment: 'bullish',
    uw_net_premium: 61_400_000,
    uw_call_put_ratio: 1.94,
    uw_unusual_score: 84,
    uw_iv_rank: 78,
    uw_dark_pool_pct: 38.9,
    tr_consensus: 'hold',
    tr_analyst_count: 38,
    tr_star_rating: 3.0,
    tr_price_target: 341.2,
    tr_upside_pct: -14.0,
    tr_success_rate: 52.8,
    tr_avg_return: 6.4,
    composite_score: 47,
    signal: 'divergent',
    notes: 'Heavy retail call flow against a below-spot street target.',
  },
  {
    ticker: 'AMD',
    company: 'Advanced Micro Devices',
    sector: 'Technology',
    price: 162.07,
    uw_sentiment: 'bullish',
    uw_net_premium: 18_900_000,
    uw_call_put_ratio: 1.77,
    uw_unusual_score: 74,
    uw_iv_rank: 55,
    uw_dark_pool_pct: 41.3,
    tr_consensus: 'buy',
    tr_analyst_count: 29,
    tr_star_rating: 4.0,
    tr_price_target: 196.4,
    tr_upside_pct: 21.2,
    tr_success_rate: 64.9,
    tr_avg_return: 19.8,
    composite_score: 79,
    signal: 'aligned_bull',
    notes: null,
  },
  {
    ticker: 'INTC',
    company: 'Intel Corp',
    sector: 'Technology',
    price: 24.63,
    uw_sentiment: 'bearish',
    uw_net_premium: -9_600_000,
    uw_call_put_ratio: 0.54,
    uw_unusual_score: 68,
    uw_iv_rank: 49,
    uw_dark_pool_pct: 47.5,
    tr_consensus: 'sell',
    tr_analyst_count: 26,
    tr_star_rating: 2.5,
    tr_price_target: 21.9,
    tr_upside_pct: -11.1,
    tr_success_rate: 48.1,
    tr_avg_return: -3.2,
    composite_score: 18,
    signal: 'aligned_bear',
    notes: 'Put spreads rolled down; two downgrades in the last week.',
  },
  {
    ticker: 'JPM',
    company: 'JPMorgan Chase & Co',
    sector: 'Financial Services',
    price: 288.94,
    uw_sentiment: 'neutral',
    uw_net_premium: 1_450_000,
    uw_call_put_ratio: 1.12,
    uw_unusual_score: 31,
    uw_iv_rank: 18,
    uw_dark_pool_pct: 53.1,
    tr_consensus: 'buy',
    tr_analyst_count: 21,
    tr_star_rating: 4.0,
    tr_price_target: 312.0,
    tr_upside_pct: 8.0,
    tr_success_rate: 69.5,
    tr_avg_return: 11.7,
    composite_score: 63,
    signal: 'neutral',
    notes: null,
  },
  {
    ticker: 'PLTR',
    company: 'Palantir Technologies',
    sector: 'Technology',
    price: 174.31,
    uw_sentiment: 'bullish',
    uw_net_premium: 27_300_000,
    uw_call_put_ratio: 2.86,
    uw_unusual_score: 88,
    uw_iv_rank: 83,
    uw_dark_pool_pct: 35.4,
    tr_consensus: 'hold',
    tr_analyst_count: 19,
    tr_star_rating: 3.0,
    tr_price_target: 149.5,
    tr_upside_pct: -14.2,
    tr_success_rate: 57.3,
    tr_avg_return: 9.9,
    composite_score: 52,
    signal: 'divergent',
    notes: 'Flow far ahead of the street; valuation is the whole disagreement.',
  },
  {
    ticker: 'XOM',
    company: 'Exxon Mobil Corp',
    sector: 'Energy',
    price: 118.72,
    uw_sentiment: 'bearish',
    uw_net_premium: -4_200_000,
    uw_call_put_ratio: 0.71,
    uw_unusual_score: 44,
    uw_iv_rank: 33,
    uw_dark_pool_pct: 46.8,
    tr_consensus: 'hold',
    tr_analyst_count: 17,
    tr_star_rating: 3.5,
    tr_price_target: 124.0,
    tr_upside_pct: 4.4,
    tr_success_rate: 61.0,
    tr_avg_return: 7.5,
    composite_score: 41,
    signal: 'neutral',
    notes: null,
  },
  {
    ticker: 'LLY',
    company: 'Eli Lilly & Co',
    sector: 'Healthcare',
    price: 812.44,
    uw_sentiment: 'bullish',
    uw_net_premium: 15_700_000,
    uw_call_put_ratio: 1.63,
    uw_unusual_score: 71,
    uw_iv_rank: 42,
    uw_dark_pool_pct: 49.2,
    tr_consensus: 'strong_buy',
    tr_analyst_count: 23,
    tr_star_rating: 4.5,
    tr_price_target: 985.0,
    tr_upside_pct: 21.2,
    tr_success_rate: 73.9,
    tr_avg_return: 24.3,
    composite_score: 85,
    signal: 'aligned_bull',
    notes: null,
  },
  {
    ticker: 'BA',
    company: 'Boeing Co',
    sector: 'Industrials',
    price: 218.06,
    uw_sentiment: 'bearish',
    uw_net_premium: -12_800_000,
    uw_call_put_ratio: 0.48,
    uw_unusual_score: 66,
    uw_iv_rank: 58,
    uw_dark_pool_pct: 40.1,
    tr_consensus: 'buy',
    tr_analyst_count: 20,
    tr_star_rating: 3.5,
    tr_price_target: 251.3,
    tr_upside_pct: 15.2,
    tr_success_rate: 55.6,
    tr_avg_return: 4.8,
    composite_score: 45,
    signal: 'divergent',
    notes: 'Put buyers paying up while the street keeps a Buy consensus.',
  },
];

export const SAMPLE_ROWS: UwTipranksRow[] = RAW.map((r, i) => ({
  ...r,
  id: `sample-${r.ticker}`,
  // Staggered so the "Updated" column doesn't read as ten identical timestamps.
  as_of: new Date(Date.UTC(2026, 8, 11, 20, 0, 0) - i * 3_600_000).toISOString(),
}));
